// English UI strings for dnd55e-compendium — the source of truth.
// Flat key → string catalog mirroring the host's /i18n/en.json shape. English
// is always present and is the universal fallback; other locales layer on top.
// NOTE: this catalog is for the addon's CHROME (page titles, labels). Game
// CONTENT names/prose live in the data records and are localized separately via
// per-locale overlay catalogs (see entry.js `localize`).

export default {
  'nav.compendium':   'Compendium',
  'page.title':       'Compendium',
  'page.intro':       'Browse D&D 5.5e (2024) content. This data also powers the character sheet when the rules engine addon is installed.',

  // ── Kind labels (plural — index sections) ────────────────────────
  'kind.classes':     'Classes',
  'kind.subclasses':  'Subclasses',
  'kind.species':     'Species',
  'kind.backgrounds': 'Backgrounds',
  'kind.feats':       'Feats',
  'kind.spells':      'Spells',
  'kind.armor':       'Armor',
  'kind.weapons':     'Weapons',
  'kind.equipment':   'Equipment',
  'kind.monsters':    'Bestiary',
  'kind.rules':       'Rules',

  // ── Kind labels (singular — detail-page tag next to the title) ───
  'kindName.class':      'Class',
  'kindName.subclass':   'Subclass',
  'kindName.species':    'Species',
  'kindName.background': 'Background',
  'kindName.feat':       'Feat',
  'kindName.spell':      'Spell',
  'kindName.armor':      'Armor',
  'kindName.weapon':     'Weapon',
  'kindName.monster':    'Monster',
  'kindName.rule':       'Rule',

  // ── Detail-metadata labels ───────────────────────────────────────
  'label.hitDie':        'Hit Die',
  'label.saves':         'Saving Throws',
  'label.spellcasting':  'Spellcasting',
  'label.mastery':       'Weapon Mastery',
  'label.subclassLevel': 'Subclass Level',
  'label.size':          'Size',
  'label.speed':         'Speed',
  'label.darkvision':    'Darkvision',
  'label.resistances':   'Resistances',
  'label.lineages':      'Lineages',
  'label.abilityScores': 'Ability Scores',
  'label.originFeat':    'Origin Feat',
  'label.skills':        'Skill Proficiencies',
  'label.category':      'Category',
  'label.prereq':        'Prerequisite',
  'label.repeatable':    'Repeatable',
  'label.levelN':        'Level {n}',
  'label.levelSchool':   'Level / School',
  'label.classes':       'Class Lists',
  'label.castingTime':   'Casting Time',
  'label.range':         'Range',
  'label.components':    'Components',
  'label.duration':      'Duration',
  'label.ritual':        'Ritual',
  'label.concentration': 'Concentration',
  'label.tags':          'Tags',
  'label.armorType':     'Type',
  'label.baseAC':        'Armor Class',
  'label.strReq':        'Strength Requirement',
  'label.stealth':       'Stealth',
  'label.damage':        'Damage',
  'label.properties':    'Properties',
  'label.ac':            'Armor Class',
  'label.hp':            'Hit Points',
  'label.cr':            'Challenge Rating',
  'label.alignment':     'Alignment',
  'label.creatureType':  'Type',
  'label.abilities':     'Ability Scores',

  // ── Value vocab ──────────────────────────────────────────────────
  'cast.full':   'full caster',
  'cast.half':   'half caster',
  'cast.third':  'third caster',
  'cast.pact':   'pact magic',
  'spell.cantrip': 'Cantrip',
  'spell.lvl':     'Level {n}',
  'feat.origin':       'Origin',
  'feat.general':      'General',
  'feat.fightingStyle': 'Fighting Style',
  'feat.epicBoon':     'Epic Boon',
  'armor.light':   'Light',
  'armor.medium':  'Medium',
  'armor.heavy':   'Heavy',
  'armor.shield':  'Shield',
  'weapon.simple':  'Simple',
  'weapon.martial': 'Martial',
  'weapon.melee':   'Melee',
  'weapon.ranged':  'Ranged',

  // ── Misc ─────────────────────────────────────────────────────────
  'misc.caster':       'caster',
  'misc.martial':      'martial',
  'misc.yes':          'Yes',
  'misc.disadvantage': 'Disadvantage',
  'misc.empty':        'No content yet.',
  'misc.unnamed':      '(unnamed)',
  'misc.back':         'Compendium',
  'misc.notFound':     'Not found',
  'misc.loading':      'Loading…',
  'misc.seedNote':     'Full 2024 ruleset — classes, species, backgrounds, feats, spells, equipment, the bestiary, and rules reference.',
  'monster.cr':        'CR {cr}',
};
